### ISSUE TITLE
Nice tool, do you plan to work on reporting?

### ISSUE THREAD

**Issue by tttp** [Alephbet/alephbet#1]
Hi,

I read your post with great interest, and I'm in the place you are when you wrote it, with an additional benefit: you did the hard work ;)

http://blog.gingerlime.com/2015/alephbet-javascript-ab-test-framework-for-developers/

have you explored fetching the result from google analytics and doing some basic reporting? Is this something you have in your todo?

X+

**Comment by gingerlime** [comment]
Thanks for your feedback, @tttp! I really appreciate it.

I'd like to explore some reporting options. I actually considered starting with keen.io, since it gives you lots of flexibility in querying your data (although it costs if you go beyond 50,000 events per month). I will also look into what's possible with Google Analytics sooner or later. I thought checking if there's some integration with google spreadsheets perhaps, but haven't got round to it yet.

I'd be happy to collaborate and build a small community around alephbet if possible. This would increase its value. Some rough ideas include: a 'recipe' library with common patterns for triggers and goals (matching cookie conditions, browser agents, URL matchers, click handlers etc), reporting tools and dashboards and so on.

Please help spread the word out if you can. It could really help. Any other contribution is welcome.

**Comment by tttp** [comment]
Hey,

Google analytics allows you to fetch the events with their api I think. we are looking into that next week probably. We might have to record the events a bit differently (eg. avoid the concatenation)

as for the recipe library, it's a good idea. Something else that might be useful is to duck tape it to cover the most simple/common examples (I need to let it sink a bit more, I'm probably going to add an issue with the suggestion when it becomes clearer)

X+

**Comment by gingerlime** [comment]
Building your own tracking adapter is very easy, so you can decide on the best event format that fits your needs - so it's easy to avoid the concatenation you mention and do it differently. This was one of the things I liked about `cohorts.js` and adopted it for alephbet (also you can plug your own storage adapter, if you prefer using cookies over localStorage for example).

I'd love to collaborate and get more ideas, so feel free to make suggestions, contribute code etc. If you need help or want to ask anything, please feel free.

**Comment by tttp** [comment]
Too early as suggestions, but started to dump them on the wiki if you want to follow/comment when it's not ready for public consumption
https://github.com/gingerlime/alephbet/wiki/Braindump-and-various-thoughts

Talking about suggestions, I'm going to be in berlin in a few weeks... and I love coffee...

**Comment by gingerlime** [comment]
Thanks @tttp - I've added some comments to the wiki page inline. Happy to continue discussing this.

**Comment by gingerlime** [comment]
And would be great to meet you for coffee if you're in town! definitely.

**Comment by gingerlime** [comment]
I created an [intro screencast](https://www.youtube.com/watch?v=NGJ0kdsxNIc&vq=hd1080) to AlephBet last night, and plan to do another one showing how to report/measure conversions using keen.io and the [Abba calculator](https://www.thumbtack.com/labs/abba/). Please let me know what you think.

**Comment by gingerlime** [comment]
@tttp - regarding the [wiki page](https://github.com/gingerlime/alephbet/wiki/Braindump-and-various-thoughts) you created. I find it hard to have a 'proper' discussion. Could you create separate issues for the various ideas you had? I find it easier to talk about each of them separately, and also see the comments 'flow'.

**Comment by tttp** [comment]
Good point, not super easy indeed. It's just that they aren't real "issues"
so far, more questions or suggestions

Will move them this PM probably

**Comment by gingerlime** [comment]
I use github issues fairly loosely. I can also use labels to mark them as idea / discussion etc - so it's easier to see at a glance. I'll do that.

**Comment by tttp** [comment]
On our side, we are trying to fetch the data out of google analytics (using their api). Bit of hacks and hardcoded bits, but seems to work.

We'll share when we get something more re-usable

**Comment by gingerlime** [comment]
Sounds good. I also played around with analytics and managed to get things into a google spreadsheet, and also via javascript. But it feels a bit tricky compared to, say, keen.io. Was hoping to share something about this as well at some point, but it's still too rough at this stage.

**Comment by gingerlime** [comment]
In case you're still interested, I created a wiki page for [displaying and analyzing experiment results](https://github.com/gingerlime/alephbet/wiki/Displaying-and-Analyzing-experiment-results). It currently has a recorded screencast showing how this can be achieved with keen.io. I plan to record another screencast pulling data from Google Analytics.

**Comment by gingerlime** [comment]
[Gimel](https://github.com/Alephbet/gimel) now includes a simple dashboard using the `gimel dashboard` command. See [here](https://github.com/Alephbet/gimel#dashboard) :)

![](https://s3.amazonaws.com/gingerlime-images/gimel-dashboard.gif "gimel dashboard")
