### ISSUE TITLE
use fetch + keepalive

### ISSUE THREAD

**Issue by gingerlime** [Alephbet/alephbet#113]
bumped into https://css-tricks.com/send-an-http-request-on-page-exit/ which describes a more reliable way to make sure requests are sent, even when the user leaves the page, using `fetch` + `keepalive`. Not sure if [older browsers support it](https://caniuse.com/fetch), or if we can use a shim. Another option is to replace the [jQuery get](https://github.com/Alephbet/alephbet/blob/1193a210cdf670e5b4dd926542cfc38c70b0c985/src/adapters/alephbet_adapter.js#L29) with a `fetch` if it's available, or fallback on the [plain JS get](https://github.com/Alephbet/alephbet/blob/1193a210cdf670e5b4dd926542cfc38c70b0c985/src/adapters/alephbet_adapter.js#L39).

**Comment by gingerlime** [comment]
@joker-777 what do you think?

**Comment by joker-777** [comment]
@gingerlime Super interesting article. I wasn't aware of this behavior. In kenhub we use [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch) as a polyfill for `fetch` but we only load it when it doesn't exist. I would simply use `fetch` + `keepalive` and let the "user" who uses Alephbet decide if he needs a polyfill or not.

**Comment by gingerlime** [comment]
So users can load a polyfill and the Alephbet code would automatically be able to use it?

**Comment by joker-777** [comment]
That's kind of what we do. We load [this js code](https://github.com/kenhub/kenhub/blob/master/app/javascript/load_polyfills.js) very early inline which checks if `fetch` or other methods exist and if one of them doesn't then we [inject this script](https://github.com/kenhub/kenhub/blob/master/app/javascript/packs/polyfills.js).

**Comment by joker-777** [comment]
Ah, and yes, once loaded, it is available for all js libraries.

**Comment by gingerlime** [comment]
Okay, but this feels like quite a lot of work for a user of Alephbet to have to worry about. I don't mind having a minimum-browser support, but then it needs to be documented clearly. Otherwise, some people might try to use it and will just get an error and won't necessarily know why. Or won't even know it can error in older browsers, and then their data is skewed.

The current JS fallback supports very old browsers, so we can also keep it like we do already (we check for jquery, but we can check if fetch is available instead). I think it's nicer to offer older-browser support out of the box if it's not super complicated for us to do that.

**Comment by joker-777** [comment]
I disagree. You would make the package bigger than necessary. Especially in the case of `then` we shouldn't worry about it because it is widely supported except for IE. If someone wants to support IE then they will use anyway polyfills which don't have to be by the way so "complicated" as we do it. They simply could include them and that's it.

**Comment by gingerlime** [comment]
We agree then :) I said it's fine to have a minimum browser support, but we just need to communicate it very clearly. And the code won't be much bigger even if we keep the fallback. We're talking about maybe 5 lines of code?

**Comment by joker-777** [comment]
Ah, ok, yes that's true. It doesn't save a lot of code.
