### ISSUE TITLE
Raise Error object instead of string

### ISSUE THREAD

**Issue by joker-777** [Alephbet/alephbet#14]
You should always raise an error object `throw new Error('some error')` instead of just throwing a string `throw 'some error'` because an error object would provide a backtrace.
It took me some time to figure out that these local storage errors we tracked on Sentry are related to AlephBet.
https://github.com/Alephbet/alephbet/blob/master/src/storage.coffee#L6

**Comment by gingerlime** [comment]
PR ? :)

**Comment by joker-777** [comment]
Yeah, just wanted to get your opinion first, before starting :)

**Comment by gingerlime** [comment]
@joker-777 are you still interested working on this? otherwise I will close this.

**Comment by joker-777** [comment]
Yes, I think so. I just forgot about it.

**Comment by gingerlime** [comment]
@joker-777 I'll close this one, but feel free to re-open if you want to implement it.

**Comment by joker-777** [comment]
@gingerlime Somehow I can't reopen it.
