### ISSUE TITLE
Cannot find `lodash.custom` when used with mocha

### ISSUE THREAD

**Issue by rbalicki2** [Alephbet/alephbet#22]
When I test a file that uses alephbet with mocha, it complains that it cannot find module `lodash.custom`, which is linked through the browser field in your package.json. Have you encountered this before? Do you have any workarounds?

As a quick brain dump, the following might fix the problem:
* A fork which uses vanilla lodash, for those of use that already use the entire lodash library and are using this with webpack
* Use a relative path to grab lodash.custom instead of a full path

Thank you! Love the module.

**Comment by gingerlime** [comment]
Hey @rbalicki2. Thanks for pointing this out and for the PR. Overall it looks good, but I'll try to take a closer look, just to make sure it doesn't break anything else.

May I ask you how you use Alephbet? Do you also use it with [Gimel](https://github.com/Alephbet/gimel) or another backend? I'm curious :)

**Comment by gingerlime** [comment]
btw, I'm not totally sure about using lodash.custom. I started it initially to keep the compiled size to a minimum, but keeping size low isn't an ultimate objective for the project. That said, it felt a bit wrong to bundle the entire lodash just for a couple of functions... I do want to make it easy for people to just add a link to Alephbet though on any page, even if they don't use npm or any build pipeline.

If you have any ideas to keep things simple, modular, but that won't bloat the standalone size, I'd love to hear and consider changes in this direction.

**Comment by rbalicki2** [comment]
@gingerlime awesome! lodash allows you to import/require just the functionality you need, e.g. `require('lodash/function/bind`)` (lodash 3) or `require('lodash/bind`)` (lodash 4). This *should* be just as good as making a custom build.

our backend: our backend is a combination of node and python. However, Alephbet doesn't really interact with it. Instead, we hook it up to segment and use alephbet to initiate experiments.

**Comment by gingerlime** [comment]
I meant the tracking backend for Alephbet ... So you're using Segment ? If you feel like contributing a tracking adapter for it, that would also be nice, so people can just plug it in... Never used segment before.

I know you can just require parts of lodash, but I think for compiling a standalone, then it would include everything, wouldn't it? I looked at it quite a long time ago, when I just started with Alephbet though, so maybe things have changed?

**Comment by gingerlime** [comment]
Thanks again for you contribution @rbalicki2. Merged your PR and released `v0.17.3` with your changes.
