### ISSUE TITLE
Multiple tracking back-ends?

### ISSUE THREAD

**Issue by PatrikTrelsmoJualo** [Alephbet/alephbet#26]
Hi!

I founds this project to be quite interesting for us, as it enables a very simple and intuitive way for us to get started with AB testing. 

However, I would like to understand if it is possible to run multiple tracking backends? 

For our specific use-case, we would want to run the Gimel backend for a simple-to-use, "just works", setup where we can evaluate tests that have clear goals. But, we would also want to send events to our own event pipeline to be able to perform more advanced analytics. 

Is there a preferred way of enabling this in the current structure? I saw the section on adding a custom tracker, but I'm not sure what the best way of sending events to multiple backends would be. 

I would assume that the best way would be to copy the Gimel Persistent Queue adapter and extend the code in the "_track"  method to also push to the dataLayer (our in-house pipeline uses Google Tag Manager). 

The alternative to this would be to extend the core to allow a list of tracking_adapter(s) and call "_track" on each one. 

Do you have any specific opinion in this matter? 

Cheers,
Patrik

**Comment by gingerlime** [comment]
Hey @PatrikTrelsmoJualo. I'm glad to hear Alephbet / Gimel are potentially useful for you guys.

You can easily create your own tracking adapter and forward to as many places as you need to. We're also using a combination of the GimelAdapter and some extra tracking that we send to Amplitude. Here's the code we use (in coffeescript).

```coffee
  class TrackingAdapter
    gimel_adapter: new AlephBet.GimelAdapter(window.gon.gimel_track_url,
                                            window.gon.gimel_namespace)
    experiment_start: (experiment, variant) ->
      # here's some custom code that only runs when the experiment starts
      extra_tracking(experiment.name, variant)
      @gimel_adapter.experiment_start(experiment, variant)
    goal_complete: (experiment, variant, goal_name, props) ->
      @gimel_adapter.goal_complete(experiment, variant, goal_name, props)

  # ... then using this adapter on the experiment
  my_experiment = new AlephBet.Experiment
    name: "experiment name..."
    tracking_adapter: new TrackingAdapter()
```

The tracking adapter should get all the important pieces of info you might need to pass it along, and therefore it's easy to build your own and/or combine with existing tracking adapters.

Hope this helps :)

**Comment by PatrikTrelsmoJualo** [comment]
Hey, 

Yes this looks like what I was thinking about. Glad to hear it works, will try it out! 

Thanks for the swift reply!

**Comment by gingerlime** [comment]
You're welcome. I'll close this for now, but if anything comes up, feel free to re-open or start a new ticket.
