### ISSUE TITLE
Is it possible to force Alephbet to use a specific variant in development?

### ISSUE THREAD

**Issue by JRKyte** [Alephbet/alephbet#31]
Hey,

I've created an experiment but I cannot see the altered version in my dev environment. The browser console shows the first variant being selected:

```
running with options: {"name":"my-test-name","tracking_adapter":{"url":"https://url.com/","namespace":"gimel-test","_queue":[]},"variants":{"1-Original":{},"2-Variant":{}},"user_id":null,"sample":1}
1-Original active
```

Is it possible to force a particular variant, e.g. the '2-Variant' test above, to be used in development?

Thanks!
Jon

**Comment by gingerlime** [comment]
Hey @JRKyte 👋 

Forcing a variant isn't internally supported by Alephbet, but perhaps a useful feature to think about.... I'm just not entirely sure about the API to implement it within Alephbet to make it easy to use for testing.

To answer your question:

First of all, it depends on the type of experiment that you're running. 

If the experiment is [user-based, with cross-device tracking](https://github.com/Alephbet/alephbet#user-based--cross-device-tracking), then for a given user id, you would always get the same variant picked (it's still random, but seeded with the id, so will always produce the same result).

You can still force a variant by updating the data in localStorage that Alephbet uses. You can do it in your browser dev tools by looking for the `alephbet` localStorage key and manipulating it. Or via the console, e.g.

```javascript
alephbet = JSON.parse(localStorage.getItem("alephbet"))
// if your experiment name is "big button", and you want to force it to pick variant "my variant"
alephbet["big button:variant"] = "my variant"
localStorage.setItem("alephbet", JSON.stringify(alephbet))
```

If the experiment isn't user-based (the default), then a new variant is picked every time you launch the experiment for the first time and stored in localStorage, so you can just clear your localStorage and refresh (or use a new incognito window) and after a few of those attempts you'd get the variant you want.

**Comment by JRKyte** [comment]
Hi @gingerlime,

Thank you, updating the data in localStorage via the console worked perfectly!
