### ISSUE TITLE
Events not posted to GA

### ISSUE THREAD

**Issue by shankarps** [Alephbet/alephbet#32]
Can you please help me with the following set up? I tried creating a basic A/B test to evaluate Alephbet. I do not see aany errors in the code. However there are no events created in Google Analytics for the experiment.

I enabled debug mode, and see this in the console.
`running with options: {"name":"button color","variants":{"green":{},"red":{}},"user_id":null,"sample":1}
`

I was also able to post a test event to Google Analytics, but the A/B test event fired by Alephbet does not show. Is there anything missing in the code? Thanks for checking.

Here is the complete page source code:

https://gist.github.com/shankarps/6dffaf3c98454fc73a21b93f2b67bcb2

**Comment by gingerlime** [comment]
Hey @shankarps. Whilst Alephbet officially supports GA, it's not a recommended tracking adapter for a variety of reasons that ultimately affect the accuracy of your tests. I would recommend taking a look at [Lamed](https://github.com/Alephbet/lamed) instead as a much better alternative.

In any case, I tested your gist the best I could, and it seems to work for me. I do not have Google Tag Manager, but I replaced the part with my GA snippet and it seems to work as expected.

```html
<html>
<head>
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="dist/alephbet.js"></script>
<script type="text/javascript">

(function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function () {
        (i[r].q = i[r].q || []).push(arguments);
    }, i[r].l = 1 * new Date();
    a = s.createElement(o), m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m);
}(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga'));
ga('create', 'UA-XXXXXXXX-X', 'auto', {
    'allowLinker': true,
    'sampleRate': 100
});

$(document).ready(function() {
  AlephBet.options.debug = true
  var button_color_experiment = new AlephBet.Experiment({
    name: 'button color',  // the name of this experiment; required.
    variants: {  // variants for this experiment; required.
      green: {
        activate: function() {  // activate function to execute if variant is selected
          $('#my-btn').attr('style', 'color: green;');
          console.log('activate blue');
        }
      },
      red: {
        activate: function() {
          $('#my-btn').attr('style', 'color: red;');
          console.log('activate red');
        }
      }
    },
  });

  // creating a goal
  var button_clicked_goal = new AlephBet.Goal('button clicked');

  $('#my-btn').on('click', function() {
  	console.log('clicked button');
    // The chosen variant will be tied to the goal automatically
    button_clicked_goal.complete();
    gtag('event', 'aaa', {
      'event_category' : 'bbb',
      'event_label' : 'ccc'
    });
  });

  // adding experiment to the goal
  button_clicked_goal.add_experiment(button_color_experiment);

  // alternatively - add the goal to the experiment
  //button_color_experiment.add_goal(button_clicked_goal);

  // tracking non-unique goals, e.g. page views
  var page_views = new AlephBet.Goal('page view', {unique: false});
});

</script>
</head>
<body>
<button id="my-btn">click me</button>
</body>
</html>
```

**Comment by shankarps** [comment]
I think it was because of a cached variable that was run earlier. This variable prevented firing  events. I was able to get both versions working (your code above and my earlier code) after clearing the cached cookies and local storage variables. Thanks for the support.
