### ISSUE TITLE
[question] Reasons for switching to basil.js?

### ISSUE THREAD

**Issue by zwacky** [Alephbet/alephbet#35]
Hey there!

I was wondering what was the reason of switching from "store" to "basil.js"?
I reverted back to alephbet@0.17.3 (with store) since basil.js has ties to `window` and threw a few stones into the way for SSR.

P.s. love alephbet 🙌
Cheers

**Comment by gingerlime** [comment]
Hey @zwacky !

I never considered Alephbet for usage on the server, although I guess in theory it should work there as well.

I don't remember precisely, but I think store wasn't so maintained and basil seemed more flexible with different fallback options etc? At my company, we used it, so I thought it makes sense to also use it with Alephbet.

@joker-777 any thoughts ?

**Comment by gingerlime** [comment]
Oh, and I completely forgot but you can actually provide your own storage adapter. See https://github.com/alephbet/alephbet#custom-storage-adapter

This means you can still use the latest Alephbet, but just provide a storage adapter using whatever you want ;-)

Nevertheless, it might be worth looking at a different default library. Suggestions welcome

**Comment by zwacky** [comment]
Hey gingerlime, thanks for your reply!
We already use custom storage adapters—actually we use pretty much all features that alephbet provides 😊.

To give a bit more context in terms of SSR:

We don't use alephbet in the server directly, it's only used in the client after hydration. 
But we use TS typings in various places directly from alephbet (e.g. `AlephBet.Goal`). That makes it part of the linting/compilation and it stumbles on the `window` references coming from basil.js (https://github.com/Wisembly/basil.js/blob/master/build/basil.js search for window).

^ This screams refactoring, but I still have so many other fires to fight. That's why I downgraded to 0.17.3 for now to unstuck myself on this particular matter.

**Comment by gingerlime** [comment]
Thanks for the added context. I'm definitely open to a better solution. Maybe simply replacing it with direct `localStorage` calls and skip the abstraction completely. If you have any suggestions or want to contribute a PR, that would be great.
