### ISSUE TITLE
link better the goal and the experiment

### ISSUE THREAD

**Issue by tttp** [Alephbet/alephbet#4]
It feels like the goal is hanging away from the experiment, not sure why. I would find clearer to have

    var button_color_experiment = new AlephBet.Experiment({ 
       name: 'button color',  // the name of this experiment; required.
       variants: {  // variants for this experiment... }
       goals: {  
         'button clicked': function (goal) { $('#my-btn').on("click", function() {goal.complete()}:}
      }
    });

This shouldn't be instead of the existing syntax (being able to re-use a goal between experiment is probably a use case), but would help for the "usual" case to keep the goal(s) at the same place of the variants

**Comment by gingerlime** [comment]
I genuinely see the point of defining the goals directly when you create an experiment, but I'm not particularly in love with this API to be honest (I'm talking about the end-user experience primarily, using AlephBet. Not about implementing this in alephbet, which looks doable):

* it seems rather oddly nested
* It's not really clear what the passed `goal` really is. I like duck typing, but when you define a `new AlephBet.Goal` things look much more explicit and clear to me.
* how do you deal with `unique: false` in this case? if you want the goal not to be unique?

Something feels odd to me with this structure. I'm really trying to wrap my head around this and find a clean way, but I can't at the moment... Will think about it more. Happy to hear what you think.

**Comment by gingerlime** [comment]
Playing devil's advocate here, can you explain what makes the code above better than this one? (this currently works).

```javascript
var button_color_experiment = new AlephBet.Experiment({ 
   name: 'button color',  // the name of this experiment; required.
   variants: {  /* variants for this experiment... */ }
});
$('#my-btn').on("click", function() { button_color_experiment.goal_complete('button clicked'); });
```

**Comment by gingerlime** [comment]
I'm closing this for now since it wasn't updated in a while, but feel free to re-open if you wish to discuss this further.
