### ISSUE TITLE
_alephbet.default.LamedAdapter is not a constructor

### ISSUE THREAD

**Issue by gingerlime** [Alephbet/alephbet#46]
after releasing 0.23.0 in #45 and also merging the missing `dist` files again in #44, it seems like when I try to import alephbet, it now fails with this error. Version 0.22.2 works

I don't think it has anything to do with the changes on #45 (it works if I load the dist minified file), so more likely the additional `dist` files that got committed? but no clue

see https://codesandbox.io/s/2wux7

**Comment by joker-777** [comment]
This is on purpose I mentioned it [here]() that you have to import it now in this way

```js
import AlephBet, {Experiment, Goal, LamedAdapter} from "alephbet";
```

Another option would be

```js
import * as AlephBet from "alephbet";
```
If you want to still access the classes with an `AlephBet` prefix.

https://codesandbox.io/s/gifted-rosalind-cn73e?file=/src/index.js

**Comment by gingerlime** [comment]
The link you sent https://codesandbox.io/s/gifted-rosalind-cn73e?file=/src/index.js still shows an error for me

![CleanShot 2021-01-10 at 12 59 26](https://user-images.githubusercontent.com/524274/104122171-b3d61c80-5343-11eb-9c7d-c7bc68631dba.png)

And also it worked with 0.22.2 but not with 0.23.0 ...

What am I missing?

**Comment by gingerlime** [comment]
https://codesandbox.io/s/607bf ok, this seems to work. Somehow codesandbox doesn't always save things properly?

![CleanShot 2021-01-10 at 13 06 41](https://user-images.githubusercontent.com/524274/104122328-b71dd800-5344-11eb-9b44-a6db0affcd27.png)

Also, the README is a bit confusing, isn't it?

It says 

```javascript
import {Experiment, Goal} from "alephbet" # ES6 module syntax
```

and then

```javascript
const button_color_experiment = new AlephBet.Experiment({
...
```

**Comment by joker-777** [comment]
Yes, it is strange. It definitely had the correct import syntax for me. Somehow it didn't save it properly. And you are right, the Readme is confusing. We should change it.

**Comment by gingerlime** [comment]
Updated README https://github.com/Alephbet/alephbet/commit/3823327d84a847939ca44cf15d72b68053556008
