### ISSUE TITLE
Test support?

### ISSUE THREAD

**Issue by Azd325** [Alephbet/alephbet#6]
Is there any plan for testing?

**Comment by gingerlime** [comment]
I neglected it, but it's definitely on the list. Any suggestions for a test framework?

**Comment by Azd325** [comment]
I heard last good things about [tape!](https://github.com/substack/tape)

**Comment by gingerlime** [comment]
Never heard of it, but I don't have a strong preference. The API felt a bit awkward to me though... particularly the `t.equal(..., ...)` feels a bit backwards. Although it just fits with the `assert ...` pattern. I guess I'm too used to rspec by now, so mocha / jasmine are a bit more familiar, that's all :)

[This post](http://www.macwright.org/2014/03/11/tape-is-cool.html) makes quite convincing arguments for using tape though. And I've read a couple of others in the same spirit (simplicity). I'll give it a try.
